version: 2.1

executors:
  build-executor:
    docker:
      - image: circleci/openjdk:11-stretch-node
    working_directory: /home/circleci/build

jobs:
  build:
    executor: build-executor
    steps:
      - checkout

      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-

      - run:
          name: Build
          command: node .circleci/ci/build.js

      - save_cache:
          paths:
            - .m2
          key: maven-repo-v1-{{ checksum "pom.xml" }}

      - persist_to_workspace:
          root: /home/circleci/build
          paths:
            - configuration.json
            - bundles/*/target/*.jar
            - content/*/target/*.zip
            - it/content/target/*.zip

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results/junit

      - run:
          name: Upload Code Coverage
          command: bash <(curl -s https://codecov.io/bash) -F unittests


  integration-test-652:
    docker:
      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-qp:6.4.3-jdk11
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS


      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-aem:6.5.2
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    working_directory: /home/circleci/repo

    steps:
      - checkout

      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-

      - attach_workspace:
          at: /home/circleci/repo

      - run:
          name: Integration tests
          command: node .circleci/ci/it-tests.js

      - store_test_results:
          path: it/http/target/failsafe-reports

      - store_artifacts:
          path: it/http/target/failsafe-reports


  integration-test-646:
    docker:
      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-qp:6.4.3-jdk8
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS


      - image: docker-adobe-cif-release.dr-uw2.adobeitc.com/circleci-aem:6.4.6
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    working_directory: /home/circleci/repo

    steps:
      - checkout

      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-

      - attach_workspace:
          at: /home/circleci/repo

      - run:
          name: Integration tests
          command: node .circleci/ci/it-tests.js

      - store_test_results:
          path: it/http/target/failsafe-reports

      - store_artifacts:
          path: it/http/target/failsafe-reports


  release:
    executor: build-executor
    steps:
      - checkout

      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-

      - run:
          name: Release
          # Only performs a 'mvn deploy' after the 'mvn release:prepare' because circleCI
          # already checks out the git tag like 'mvn release:perform' would do.
          # The "skip-it" property ensures that we do not release the integration tests sub-modules
          command: |
            echo $GPG_PRIVATE_KEY | base64 --decode | gpg --batch --import
            mvn -B -s /home/circleci/project/.circleci/settings.xml clean deploy -Prelease-sign-artifacts -Dskip-it
            rm -rf /home/circleci/.gnupg


workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - integration-test-652:
          filters:
            tags:
              only: /.*/
          requires:
            - build

      - integration-test-646:
          filters:
            tags:
              only: /.*/
          requires:
            - build
              
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^cif-connector-reactor-\d+\.\d+\.\d+$/
